# -*- coding: utf-8 -*-
"""Taller_en_Clase_(POO_en_Python)_Figuras_Geométricas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/raul-rabascall/Actividad-en-clase-POO-ves/blob/main/Taller_en_Clase_(POO_en_Python)_Figuras_Geom%C3%A9tricas.ipynb
"""

"""
Sistema de Figuras Geométricas

Descripción general:
Implementar un conjunto de clases orientadas a modelar figuras
geométricas aplicando principios fundamentales de la Programación Orientada
a Objetos (POO) en Python.

- Aplicar encapsulamiento mediante propiedades (@property) y atributos privados.
- Implementar herencia múltiple para reutilización de comportamiento.
- Definir contratos de comportamiento (métodos area y perimetro).
- Sobrescribir métodos especiales (__str__) para representación legible.
- Garantizar integridad de datos mediante validaciones.

Estructura conceptual:
- FiguraGeometrica → Clase base con dimensiones
- Color → Clase complementaria para composición de atributos
- Clases derivadas → Cuadrado, Rectangulo, Circunferencia

"""

import math

class FiguraGeometrica:
    """

    - Gestionar atributos dimensionales (alto y ancho).
    - Garantizar encapsulamiento mediante atributos privados.
    - Validar la integridad de los datos de entrada.

    Atributos:
        __alto (float): Dimensión vertical de la figura.
        __ancho (float): Dimensión horizontal de la figura.

    Diseño:
    Se emplea encapsulamiento fuerte utilizando doble guion bajo (__)
    y acceso controlado mediante propiedades.
    """

    def __init__(self, alto, ancho):
        self.alto = alto
        self.ancho = ancho

    @property
    def alto(self):
        """Retorna el valor del alto."""
        return self.__alto

    @alto.setter
    def alto(self, valor):
        """
        Establece el valor del alto con validación.

        Args:
            valor (float): Nuevo valor del alto.

        Raises:
            ValueError: Si el valor no es positivo.
        """
        if valor > 0:
            self.__alto = valor
        else:
            raise ValueError("El alto debe ser positivo")

    @property
    def ancho(self):
        """Retorna el valor del ancho."""
        return self.__ancho

    @ancho.setter
    def ancho(self, valor):
        """
        Establece el valor del ancho con validación.

        Args:
            valor (float): Nuevo valor del ancho.

        Raises:
            ValueError: Si el valor no es positivo.
        """
        if valor > 0:
            self.__ancho = valor
        else:
            raise ValueError("El ancho debe ser positivo")

    def __str__(self):
        """
        Retorna una representación textual de la figura.

        Returns:
            str: Cadena descriptiva de dimensiones.
        """
        return f"Alto: {self.__alto}, Ancho: {self.__ancho}"

class Color:
    """
    Clase que encapsula el atributo de color de una figura.


    - Gestionar el atributo color de forma encapsulada.
    - Validar que el color sea un valor válido (no vacío).

    Atributos:
        __color (str): Representación textual del color.

    Diseño:
    Se utiliza como clase complementaria para ser combinada mediante
    herencia múltiple con otras clases geométricas.
    """

    def __init__(self, color):
        self.color = color

    @property
    def color(self):
        """Obtiene el color de la figura."""
        return self.__color

    @color.setter
    def color(self, valor):
        """
        Establece el color con validación.

        Args:
            valor (str): Nombre del color.

        Raises:
            ValueError: Si el valor es vacío.
        """
        if valor:
            self.__color = valor
        else:
            raise ValueError("El color no puede estar vacío")

    def __str__(self):
        """
        Representación textual del color.

        Returns:
            str: Cadena con el color.
        """
        return f"Color: {self.__color}"

class Cuadrado(FiguraGeometrica, Color):
    """

    - Hereda comportamiento de FiguraGeometrica y Color.
    - Define cálculo específico de área y perímetro.

    Restricciones:
    - Todos los lados deben ser iguales.
    - El valor del lado debe ser positivo.

    Métodos:
        area(): Calcula el área del cuadrado.
        perimetro(): Calcula el perímetro del cuadrado.
    """

    def __init__(self, lado, color):
        if lado <= 0:
            raise ValueError("El lado debe ser positivo")

        FiguraGeometrica.__init__(self, lado, lado)
        Color.__init__(self, color)

    def area(self):
        """Calcula el área del cuadrado."""
        return self.alto ** 2

    def perimetro(self):
        """Calcula el perímetro del cuadrado."""
        return 4 * self.alto

    def __str__(self):
        """
        Representación completa del cuadrado.

        Returns:
            str: Información estructurada del objeto.
        """
        return (
            f"Cuadrado -> {FiguraGeometrica.__str__(self)}, "
            f"{Color.__str__(self)}, "
            f"Área: {self.area()}, Perímetro: {self.perimetro()}"
        )

class Rectangulo(FiguraGeometrica, Color):
    """

    - Hereda dimensiones y color.
    - Permite lados de diferente longitud.

    Métodos:
        area(): Calcula el área del rectángulo.
        perimetro(): Calcula el perímetro del rectángulo.
    """

    def __init__(self, alto, ancho, color):
        FiguraGeometrica.__init__(self, alto, ancho)
        Color.__init__(self, color)

    def area(self):
        """Calcula el área."""
        return self.alto * self.ancho

    def perimetro(self):
        """Calcula el perímetro."""
        return 2 * (self.alto + self.ancho)

    def __str__(self):
        return (
            f"Rectángulo -> {FiguraGeometrica.__str__(self)}, "
            f"{Color.__str__(self)}, "
            f"Área: {self.area()}, Perímetro: {self.perimetro()}"
        )

class Circunferencia(FiguraGeometrica, Color):
    """

    - Se reutiliza el atributo 'alto' como radio.
    - Se mantiene compatibilidad con la clase base.

    Restricciones:
    - El radio debe ser un valor positivo.

    Métodos:
        area(): Calcula el área del círculo.
        perimetro(): Calcula la longitud de la circunferencia.
    """

    def __init__(self, radio, color):
        if radio <= 0:
            raise ValueError("El radio debe ser positivo")

        FiguraGeometrica.__init__(self, radio, radio)
        Color.__init__(self, color)

    def area(self):
        """Calcula el área."""
        return math.pi * self.alto ** 2

    def perimetro(self):
        """Calcula el perímetro."""
        return 2 * math.pi * self.alto

    def __str__(self):
        return (
            f"Circunferencia -> Radio: {self.alto}, "
            f"{Color.__str__(self)}, "
            f"Área: {self.area():.2f}, "
            f"Perímetro: {self.perimetro():.2f}"
        )

if __name__ == "__main__":
    """

    - Ejecutar pruebas controladas de las clases.
    - Validar comportamiento correcto.
    - Mostrar resultados de área y perímetro.

    Manejo de errores:
    - Captura excepciones de validación (ValueError).
    """

    print(" PRUEBAS DEL SISTEMA \n")

    try:
        cuadrado = Cuadrado(5, "Rojo")
        print(cuadrado)
        print()

        rectangulo = Rectangulo(4, 6, "Azul")
        print(rectangulo)
        print()

        circunferencia = Circunferencia(3, "Verde")
        print(circunferencia)
        print()

        print("=== FIN DE PRUEBAS ===")

    except ValueError as error:
        print("Error detectado:", error)

"""
Aplicación de Polimorfismo

Se utilizan funciones genéricas capaces de trabajar
con múltiples tipos de objetos geométricos.

Cada objeto responde de forma diferente a los métodos:
- area()
- perimetro()

Esto demuestra el principio de polimorfismo.
"""


def sumar_areas(figuras_geometricas):
    """
    Suma las áreas de todas las figuras.

    Args:
        figuras_geometricas (list): Lista de figuras.

    Returns:
        float: Total de áreas.
    """

    suma_areas = 0

    for figura in figuras_geometricas:
        suma_areas += figura.area()

    return suma_areas


def sumar_perimetros(figuras_geometricas):
    """
    Suma los perímetros de todas las figuras.

    Args:
        figuras_geometricas (list): Lista de figuras.

    Returns:
        float: Total de perímetros.
    """

    suma_perimetros = 0

    for figura in figuras_geometricas:
        suma_perimetros += figura.perimetro()

    return suma_perimetros


# Lista de objetos polimórficos
figuras = [
    Cuadrado(4, "Rojo"),
    Rectangulo(5, 8, "Azul"),
    Circunferencia(3, "Verde")
]

print("=== POLIMORFISMO ===\n")

print(f"Suma total de áreas: {sumar_areas(figuras):.2f}")
print(f"Suma total de perímetros: {sumar_perimetros(figuras):.2f}")

# -*- coding: utf-8 -*-
"""CORRECCION_POLI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t67GP47jG4QvTm4-5Ks9VHZRCO9WAxAn

CHALEN MARTINEZ CAMILA

CHALEN MARTINEZ CAMILA
"""

"""
README - Figuras Geométricas

Este programa implementa clases usando herencia múltiple para representar
figuras geométricas con color.

Clases:
- FiguraGeometrica (base)
- Color
- Cuadrado
- Rectangulo
- Circunferencia

Funcionalidades:
- Cálculo de área
- Cálculo de perímetro
- Validación de datos (no negativos, no vacíos)
- Aplicación de polimorfismo mediante el uso de métodos
  compartidos como area() y perimetro() en diferentes figuras.

Estudiante: [Chalen Martinez Camila]
Fecha: [06-05-2026]
"""
import math


class FiguraGeometrica:
    def __init__(self, alto: float, ancho: float):
        self.alto = alto
        self.ancho = ancho

    @property
    def alto(self) -> float:
        return self.__alto

    @alto.setter
    def alto(self, valor: float):
        if valor > 0:
            self.__alto = valor
        else:
            raise ValueError("El alto debe ser positivo")

    @property
    def ancho(self) -> float:
        return self.__ancho

    @ancho.setter
    def ancho(self, valor: float):
        if valor > 0:
            self.__ancho = valor
        else:
            raise ValueError("El ancho debe ser positivo")

    def __str__(self) -> str:
        return f"Figura geometrica: Alto: {self.alto}, Ancho: {self.ancho}"

'''
CLASE QUE PERMITE CREAR UN OBJETO DEL TIPO COLOR
'''
class Color:
    def __init__(self, color: str):
        self.color = color

    @property
    def color(self) -> str:
        return self._color

    @color.setter
    def color(self, valor: str):
        if valor and isinstance(valor, str):
            self._color = valor.strip()
        else:
            raise ValueError("El color no puede estar vacío")

    def __str__(self) -> str:
        return f"Color: {self._color}"


class Cuadrado(FiguraGeometrica, Color):
    '''
    CREA OBJETOS DE TIPO CUADRADO
    '''
    def __init__(self, lado: float, color: str):
        FiguraGeometrica.__init__(self, lado, lado)
        Color.__init__(self, color)

    def area(self) -> float:
        return self.alto ** 2

    def perimetro(self) -> float:
        return 4 * self.alto

    def __str__(self) -> str:
        return f"Cuadrado -> {FiguraGeometrica.__str__(self)}, {Color.__str__(self)}"

'''
CLASE QUE PERMITE CREAR UN OBJETO DEL TIPO RECTANGULO
'''
class Rectangulo(FiguraGeometrica, Color):

    def __init__(self, alto: float, ancho: float, color: str):
        FiguraGeometrica.__init__(self, alto, ancho)
        Color.__init__(self, color)

    def area(self) -> float:
        return self.alto * self.ancho

    def perimetro(self) -> float:
        return 2 * (self.alto + self.ancho)

    def __str__(self) -> str:
        return f"Rectángulo -> {FiguraGeometrica.__str__(self)}, {Color.__str__(self)}"


class Circunferencia(FiguraGeometrica, Color):
    def __init__(self, radio: float, color: str):
        FiguraGeometrica.__init__(self, radio, radio)
        Color.__init__(self, color)

    def area(self) -> float:
        return math.pi * (self.alto ** 2)

    def perimetro(self) -> float:
        return 2 * math.pi * self.alto

    def __str__(self) -> str:
        return f"Circunferencia -> Radio: {self.alto}, {Color.__str__(self)}"



# PRUEBAS
if __name__ == "__main__":


    c = Cuadrado(5, "Rojo")
    print(c)
    print("Área:", round(c.area(), 2))
    print("Perímetro:", round(c.perimetro(), 2))
    print()

    r = Rectangulo(4, 6, "Azul")
    print(r)
    print("Área:", round(r.area(), 2))
    print("Perímetro:", round(r.perimetro(), 2))
    print()

    cir = Circunferencia(3, "Verde")
    print(cir)
    print("Área:", round(cir.area(), 2))
    print("Perímetro:", round(cir.perimetro(), 2))

"""POLIMORFISMO"""

'''
POLIMORFISMO
'''

def sumar_areas(figuras_geometricas):
    suma_areas = 0

    for figura in figuras_geometricas:
        suma_areas += figura.area()

    return suma_areas


def sumar_perimetros(figuras_geometricas):
    suma_perimetros = 0

    for figura in figuras_geometricas:
        suma_perimetros += figura.perimetro()

    return suma_perimetros


print("\n--- POLIMORFISMO ---\n")

# Lista con diferentes objetos
figuras = [
    Cuadrado(5, "Rojo"),
    Rectangulo(4, 6, "Azul"),
    Circunferencia(3, "Verde")
]

# Mostrar cada figura
for figura in figuras:
    print(figura)
    print("Área:", round(figura.area(), 2))
    print("Perímetro:", round(figura.perimetro(), 2))
    print()

# Suma total
print("Suma total de áreas:", round(sumar_areas(figuras), 2))
print("Suma total de perímetros:", round(sumar_perimetros(figuras), 2))